using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ArbetsWatch.Core.Places;

public sealed record Municipality(string Id, string Label, string Code, string RegionId);

public sealed record Region(string Id, string Label, string Code, IReadOnlyList<Municipality> Municipalities);

/// <summary>
/// Swedish län and kommuner bundled as <c>Places/places.json</c> (generated by <c>tools/TaxonomyExport</c>).
/// Loaded once; works offline.
/// </summary>
public sealed class PlaceCatalog
{
    public const string SwedenId = "i46j_HmG_v64";

    private readonly FrozenDictionary<string, Region> _regions;
    private readonly FrozenDictionary<string, Municipality> _municipalities;

    private PlaceCatalog(PlacesDocument document)
    {
        SchemaVersion = document.SchemaVersion;
        TaxonomyVersion = document.TaxonomyVersion;
        GeneratedUtc = document.GeneratedUtc;
        Regions = [.. document.Regions.Select(r => new Region(
            r.Id, r.Label, r.Code,
            [.. r.Municipalities.Select(m => new Municipality(m.Id, m.Label, m.Code, m.RegionId))]))];
        _regions = Regions.ToFrozenDictionary(r => r.Id, StringComparer.Ordinal);
        _municipalities = Regions.SelectMany(r => r.Municipalities)
            .ToFrozenDictionary(m => m.Id, StringComparer.Ordinal);
    }

    public int SchemaVersion { get; }

    public int TaxonomyVersion { get; }

    public DateTimeOffset GeneratedUtc { get; }

    /// <summary>Regions ordered by their official code (01 Stockholm … 25 Norrbotten).</summary>
    public IReadOnlyList<Region> Regions { get; }

    public IEnumerable<Municipality> Municipalities => Regions.SelectMany(r => r.Municipalities);

    public Region? FindRegion(string id) => _regions.GetValueOrDefault(id);

    public Municipality? FindMunicipality(string id) => _municipalities.GetValueOrDefault(id);

    public static PlaceCatalog LoadBundled()
    {
        using var stream = typeof(PlaceCatalog).Assembly.GetManifestResourceStream("ArbetsWatch.Core.Places.places.json")
            ?? throw new InvalidOperationException("The bundled places.json resource is missing.");
        return Load(stream);
    }

    public static PlaceCatalog Load(Stream json)
    {
        var document = JsonSerializer.Deserialize(json, PlacesJsonContext.Default.PlacesDocument)
            ?? throw new InvalidDataException("places.json is empty.");
        if (document.SchemaVersion != 1)
        {
            throw new InvalidDataException($"Unsupported places.json schema version {document.SchemaVersion}.");
        }

        return new PlaceCatalog(document);
    }
}

internal sealed record PlacesDocument(
    int SchemaVersion,
    DateTimeOffset GeneratedUtc,
    int TaxonomyVersion,
    IReadOnlyList<PlacesRegion> Regions);

internal sealed record PlacesRegion(string Id, string Label, string Code, IReadOnlyList<PlacesMunicipality> Municipalities);

internal sealed record PlacesMunicipality(string Id, string Label, string Code, string RegionId);

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(PlacesDocument))]
internal sealed partial class PlacesJsonContext : JsonSerializerContext;
